
import "./globals.css";

import { CartProvider } from "@/context/CartContext";

import { Toaster } from 'react-hot-toast';


export const metadata = {
  title: "Deshi Food Villa",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={` bg-[#f9f6f3] min-h-screen font-sans`}
      >
        <CartProvider>
          {children}
          <Toaster position="top-right" />
        </CartProvider>
        
      </body>
    </html>
  );
}
